sonar.projectKey=Solaris-CET_solaris-cet
sonar.projectName=solaris-cet
sonar.sources=app/src,api,contracts,scripts
sonar.tests=app/src
sonar.test.inclusions=app/src/**/*.{test,spec}.{ts,tsx}
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/.api-dist/**,**/coverage/**,**/public/**

