server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            msg: msg
            request_id: request_id
            trace_id: trace_id
            span_id: span_id
            method: method
            path: path
            status: status
            duration_ms: duration_ms
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

