type CounterKey = string;

const counters = new Map<CounterKey, number>();

function inc(key: CounterKey, by = 1): void {
  counters.set(key, (counters.get(key) ?? 0) + by);
}

function esc(v: string): string {
  return String(v).replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/"/g, '\\"');
}

function key(name: string, labels: Record<string, string>): string {
  const sorted = Object.keys(labels)
    .sort()
    .map((k) => `${k}=${labels[k]}`)
    .join('|');
  return `${name}|${sorted}`;
}

export type AiProviderUsage = {
  provider: string;
  model: string;
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  costUsd?: number;
};

export function recordAiChatMetrics(input: {
  outcome: 'ok' | 'error';
  cache: 'hit' | 'miss';
  providers: Array<{ provider: string; model: string }>;
  durationMs?: number;
  providerUsage?: AiProviderUsage[];
  totalCostUsd?: number;
}): void {
  const providersLabel = input.providers.length
    ? input.providers
        .map((p) => `${p.provider}:${p.model}`)
        .slice(0, 4)
        .join(',')
    : 'none';
  inc(key('solaris_ai_chat_requests_total', { outcome: input.outcome, cache: input.cache, providers: providersLabel }));

  if (typeof input.durationMs === 'number' && Number.isFinite(input.durationMs)) {
    inc(key('solaris_ai_chat_duration_ms_sum', { outcome: input.outcome, cache: input.cache, providers: providersLabel }), input.durationMs);
    inc(key('solaris_ai_chat_duration_ms_count', { outcome: input.outcome, cache: input.cache, providers: providersLabel }));
  }

  for (const p of input.providerUsage ?? []) {
    const labels = { provider: p.provider, model: p.model };
    if (typeof p.promptTokens === 'number') inc(key('solaris_ai_tokens_prompt_total', labels), p.promptTokens);
    if (typeof p.completionTokens === 'number') inc(key('solaris_ai_tokens_completion_total', labels), p.completionTokens);
    if (typeof p.totalTokens === 'number') inc(key('solaris_ai_tokens_total', labels), p.totalTokens);
    if (typeof p.costUsd === 'number') inc(key('solaris_ai_cost_usd_total', labels), p.costUsd);
  }

  if (typeof input.totalCostUsd === 'number') {
    inc(key('solaris_ai_cost_usd_total', { provider: 'total', model: 'all' }), input.totalCostUsd);
  }
}

export function formatAiPromMetrics(): string {
  const lines: string[] = [];
  const entries = [...counters.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

  const emit = (metric: string, labels: Record<string, string>, value: number) => {
    const labelStr = Object.keys(labels)
      .sort()
      .map((k) => `${k}="${esc(labels[k])}"`)
      .join(',');
    lines.push(`${metric}{${labelStr}} ${Number.isFinite(value) ? value : 0}`);
  };

  const metricOrder = [
    'solaris_ai_chat_requests_total',
    'solaris_ai_chat_duration_ms_sum',
    'solaris_ai_chat_duration_ms_count',
    'solaris_ai_tokens_prompt_total',
    'solaris_ai_tokens_completion_total',
    'solaris_ai_tokens_total',
    'solaris_ai_cost_usd_total',
  ];

  for (const m of metricOrder) {
    lines.push(`# HELP ${m} Generated by CET AI runtime.`, `# TYPE ${m} counter`);
    for (const [k, v] of entries) {
      const [name, rest] = k.split('|', 2);
      if (name !== m) continue;
      const labels: Record<string, string> = {};
      const labelPairs = rest ? rest.split('|').filter(Boolean) : [];
      for (const pair of labelPairs) {
        const idx = pair.indexOf('=');
        if (idx <= 0) continue;
        labels[pair.slice(0, idx)] = pair.slice(idx + 1);
      }
      emit(m, labels, v);
    }
    lines.push('');
  }

  return lines.join('\n');
}

