[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 20

[sshd]
enabled = true

[nginx-botsearch]
enabled = true
port = http,https
logpath = /var/log/nginx/access.log

[nginx-http-auth]
enabled = true
port = http,https
logpath = /var/log/nginx/error.log
